### ISSUE TITLE
Link GitHub Pages in README.md

### ISSUE THREAD

**Issue by WirelessAether** [EpistasisLab/tpot2#39]
Reaching the GitHub Pages from the main site of the repository as a first-time user is counterintuitive and takes too many clicks.

## Context of the issue
I was reading this repository for the first time and wanted to find the documentation for the individual functions and inner classes but did not see it in the code; therefore, I went to open an issue about the lack of documentation, found issue #1, and all the way at its bottom issue #21, at the bottom of which I found the link to the GitHub pages.

## Process to reproduce the issue
Use the repository for the first time without knowing where to find this documentation.

## Expected result
This documentation would be easier-to-find.

## Current result
This documentation is hard-to-find.

## Possible fix
Link the GitHub pages in the README.md.  
Here's the link text: https://jay-m-dev.github.io/tpot2/
Here it is as a clickable [link](https://jay-m-dev.github.io/tpot2/), which could be put in the README.md for new readers to easily find.

**Comment by perib** [comment]
added a link to the readme, thanks for the suggestion. 

I agree that more documentation is needed. As that is already covered in issue #1, I will close this issue.
