### ISSUE TITLE
Error in Tutorial 7

### ISSUE THREAD

**Issue by AdamFinkle** [EpistasisLab/tpot2#41]
I tried running Tutorial 7 but got an error in the first cell.

## Context of the issue

I wanted to try TPOT2 to benchmark it.  I cloned the repository, opened Jupyter, ran Tutorial 7, and got a red error box under the first cell.

## Process to reproduce the issue
1. Clone the git repository
2. Open Jupyter
3. Run the first code block of Tutorial 7

## Expected result

I don't know what I should have expected exactly, but I did expect the code would run.

## Current result
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 13
     11 X, y = sklearn.datasets.load_digits(return_X_y=True)
     12 X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, train_size=0.75, test_size=0.25)
---> 13 est = tpot2.TPOTClassifier(population_size= 8, generations=5,)
     14 est.fit(X_train, y_train)
     15 print(scorer(est, X_test, y_test))

TypeError: TPOTClassifier.__init__() got an unexpected keyword argument 'population_size'
```

**Comment by perib** [comment]
Sorry about that.
Should be fixed now in the dev branch
