### ISSUE TITLE
Need to update the conda package to the latest version of TPOT2 (can this be automatic? )

### ISSUE THREAD

**Issue by perib** [EpistasisLab/tpot2#56]

**Comment by jay-m-dev** [comment]
conda-forge has a bot that automatically checks for version updates in PyPI. see the [conda-forge docs](https://conda-forge.org/docs/maintainer/updating_pkgs.html).
The tpot2-feedstock repository is here: https://github.com/conda-forge/tpot2-feedstock
At the next tpot2 release, let's keep an eye out for this to be properly automated. We can check the status of the conda-forge processes here: https://conda-forge.org/status/

**Comment by jay-m-dev** [comment]
Enabled the conda-forge bot. It automatically created the PR to publish the package to conda-forge.
I forked the feedstock here: [EpistasisLab/tpot2-feedstock](https://github.com/EpistasisLab/tpot2-feedstock).
I added @nickotto, @perib and epistasislab as feedstock maintainers.
I'm not convinced this is fully automated yet, so let's keep this issue open and monitor at the next release.

**Comment by jay-m-dev** [comment]
The conda-forge package was successfully uploaded by the automerge-bot. See this link for details: https://github.com/conda-forge/tpot2-feedstock/pull/7#issuecomment-1815676668
